language: php

php:
    - 5.5
    - 5.6
    - hhvm
    
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install

script:
  - bin/phpspec run
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

